### ISSUE TITLE
ROCm 6.2 support

### ISSUE THREAD

**Issue by nikhil-tensorwave** [Looong01/pyg-rocm-build#4]
I am trying to install PyTorch-Geometric on a ROCm 6.2 system with MI300Xs, but I am getting the error "ImportError: libamdhip64.so.5: cannot open shared object file: No such file or directory" when I install PyTorch 2.3.1 using the ROCm 6.0 wheel.

If I install PyTorch 2.3 using the ROCm 5.7 wheel, I get the error: "Compile with TORCH_USE_CUDA_DSA to enable device-side assertions."

System:
Ubuntu 22.04
ROCm 6.2
Python 3.10

**Comment by Looong01** [comment]
Sorry for long wait.

Upgrading finished.
https://github.com/Looong01/pyg-rocm-build/releases/tag/6

U can try this.
