### ISSUE TITLE
Steps to build the ROCm wheels for torch_geometric and torch_cluster

### ISSUE THREAD

**Issue by Akhil-CM** [Looong01/pyg-rocm-build#5]
Hi,

I am following the steps given in [official AMD ROCm pytorch steps using ubuntu 24.04 docker image](https://rocm.docs.amd.com/projects/install-on-linux/en/develop/install/3rd-party/pytorch-install.html)

I would like to know what process you used to build the wheels in this repo. I read the comments in the [discussion you made here](https://github.com/pyg-team/pytorch_geometric/discussions/6370). But I didn't get a successfull installation. Here's the steps I am following ([pretty much the steps here](https://rocm.docs.amd.com/projects/install-on-linux/en/develop/install/3rd-party/pytorch-install.html)):
1. Download and run the [docker image](https://hub.docker.com/r/rocm/dev-ubuntu-24.04) as mentioned [here](https://rocm.docs.amd.com/projects/install-on-linux/en/develop/install/3rd-party/pytorch-install.html)
2. `sudo apt update`
3. `sudo apt install libjpeg-dev python3-dev python3-pip`
4. 
```
wget "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
bash Miniforge3-$(uname)-$(uname -m).sh -p "/opt/mamba"
``` 
5. Close shell and reopen
6. `mamba create -n PyG python=3.12`
7. `mamba activate PyG`
8. `pip3 install wheel setuptools`
9. `pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm6.2/`
10. Follow the steps [here](https://github.com/pyg-team/pytorch_geometric/discussions/6370#discussioncomment-4791326)

**Comment by Looong01** [comment]
Let me take an example
1. ```docker pull rocm/pytorch:rocm6.1.3_ubuntu22.04_py3.10_pytorch_release-2.1.2```
2. ```docker run -itd --name rocm6.1.3 --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --device=/dev/kfd --device=/dev/dri --group-add video --ipc=host --shm-size 32G rocm/pytorch:rocm6.1.3_ubuntu22.04_py3.10_pytorch_release-2.1.2```
3. Run and attach this docker container by VSCode.
4. Install Miniconda3
5. ```conda create -n py310 python=3.10 -y```
6. ```conda activate py310```
7. ```pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm6.1/```
8. Follow the steps [here](https://github.com/pyg-team/pytorch_geometric/discussions/6370#discussioncomment-4791326)

**Comment by Akhil-CM** [comment]
Thanks for the details. Using the pre-built wheels from this repo gave a working installation. When I have free time, I test out the building from the source again. I'll close the issue for now.

**Comment by Akhil-CM** [comment]
@Looong01 did you have any "thrust/complex.h" related errors when you followed the step above?
Is it possible that I'm getting this error due to using `docker pull rocm/dev-ubuntu-24.04:latest`

**Comment by Looong01** [comment]
I don't try that image, so I don't know. But I just met this kind of import errors when I used the released source codes. But after I turn to the main branch of the repos, I never met it again.

**Comment by Akhil-CM** [comment]
@Looong01 I found an interesting issue when I'm installing PyG related libs (torch_geometric, scatter, cluster) by following the [steps here](https://github.com/pyg-team/pytorch_geometric/discussions/6370#discussioncomment-4791326).

when I directly install from the git repo, I have issues with my installation like symbols not found or not compiled for CUDA. But when I do `python3 setup.py bdist_wheel` and then `pip install` the wheel, everything is fine.

Another thing, in the [build.sh](https://github.com/Looong01/pyg-rocm-build/blob/main/build.sh) script, I see that you take [torch_geometric wheels from pythonhosted](https://github.com/Looong01/pyg-rocm-build/blob/9b2212810dc0a6b6aa5d3313a897b693bdcc6d02/build.sh#L59). Do you build the wheels and upload it there?

**Comment by Looong01** [comment]
> [@Looong01](https://github.com/Looong01) I found an interesting issue when I'm installing PyG related libs (torch_geometric, scatter, cluster) by following the [steps here](https://github.com/pyg-team/pytorch_geometric/discussions/6370#discussioncomment-4791326).
> 
> when I directly install from the git repo, I have issues with my installation like symbols not found or not compiled for CUDA. But when I do `python3 setup.py bdist_wheel` and then `pip install` the wheel, everything is fine.
> 
> Another thing, in the [build.sh](https://github.com/Looong01/pyg-rocm-build/blob/main/build.sh) script in your repo, I see that you take [torch_geometric wheels from pythonhosted](https://github.com/Looong01/pyg-rocm-build/blob/9b2212810dc0a6b6aa5d3313a897b693bdcc6d02/build.sh#L59). Do you build the wheels and upload it there? Do you build the wheels the same way as the other packages in the for loop of the script?

First, I dont know about it. Its really weird. 

And I think there is no necessary to build wheel of torch_geometric by source, cuz there is no CUDA codes inside, meaning no specific hardware, GPU architecture, binding. And the build script in my repo is just providing convenience for myself.

**Comment by Akhil-CM** [comment]
> First, I dont know about it. Its really weird.

Let me know if you have a similar issue, direct install vs building wheel + wheel install. I might open an issue at upstream if it's not specific to my machine

> And I think there is no necessary to build wheel of torch_geometric by source, cuz there is no CUDA codes inside, meaning no specific hardware, GPU architecture, binding. And the build script in my repo is just providing convenience for myself.

Good to know. Thanks

**Comment by Looong01** [comment]
> > First, I dont know about it. Its really weird.
> 
> Let me know if you have a similar issue, direct install vs building wheel + wheel install. I might open an issue at upstream if it's not specific to my machine
> 
> > And I think there is no necessary to build wheel of torch_geometric by source, cuz there is no CUDA codes inside, meaning no specific hardware, GPU architecture, binding. And the build script in my repo is just providing convenience for myself.
> 
> Good to know. Thanks

Yeah it's not specific to your or my machine.
